/** MelonClaw visual primitives. CSS and Ant Design consume this same source. */
export const tokens = {
  "canvas": "#f5f5f7",
  "panel": "#ffffff",
  "sidebar": "rgba(246, 246, 248, 0.82)",
  "ink": "#1d1d1f",
  "muted": "#6e6e73",
  "line": "#e1e2e6",
  "hover": "rgba(0, 0, 0, 0.05)",
  "fill-active": "rgba(0, 0, 0, 0.08)",
  "brand-primary": "#0071e3",
  "brand-primary-hover": "#0077ed",
  "brand-soft": "rgba(0, 113, 227, 0.1)",
  "brand-coral": "#ff375f",
  "brand-coral-soft": "rgba(255, 55, 95, 0.08)",
  "brand-seed": "#1d1d1f",
  "status-success": "#248a3d",
  "status-warning": "#b25000",
  "status-warning-bg": "#fff4e5",
  "status-error": "#d70015",
  "status-error-bg": "#fff0f0",
  "shadow-card": "none",
  "shadow-composer": "none",
  "shadow-pop": "0 4px 16px rgba(0, 0, 0, 0.10)",
  "sidebar-width": "260px",
  "sidebar-collapsed-width": "64px",
  "content-max-width": "800px",
  "radius-control": "6px",
  "radius-card": "8px",
  "radius-composer": "12px",
  "ease-apple": "cubic-bezier(0.25, 0.1, 0.25, 1)",
  "duration-fast": "200ms",
  "font-ui": "-apple-system, BlinkMacSystemFont, \"SF Pro Text\", \"SF Pro Display\",\n    \"PingFang SC\", \"Helvetica Neue\", \"Segoe UI\", \"Microsoft YaHei\",\n    ui-sans-serif, system-ui, sans-serif",
  "font-mono": "ui-monospace, \"SF Mono\", SFMono-Regular, Menlo, Monaco,\n    Consolas, monospace",
  "text-xs": "12px",
  "text-sm": "13px",
  "text-md": "14px",
  "text-base": "14px",
  "text-lg": "16px",
  "text-xl": "18px",
  "text-title": "24px",
  "radius-overlay": "12px",
  "radius-sm": "4px",
  "line-light": "#eef0f3",
  "line-strong": "#b8b8bd",
  "tertiary": "#86868b",
  "disabled-text": "#a1a1a6",
  "disabled-bg": "#f1f1f3",
  "shadow-modal": "0 12px 40px rgba(0, 0, 0, 0.14)",
  "line-height-base": "22px",
  "line-height-sm": "20px",
  "line-height-xs": "18px",
  "line-height-title": "32px",
  "line-height-section": "26px",
  "weight-regular": "400",
  "weight-medium": "500",
  "weight-semibold": "600",
  "control-height-sm": "28px",
  "control-height-md": "32px",
  "control-height-lg": "40px",
  "control-height-touch": "44px",
  "icon-xs": "12px",
  "icon-sm": "14px",
  "icon-md": "16px",
  "icon-lg": "18px",
  "icon-nav": "20px",
  "icon-feature": "24px",
  "icon-gap": "6px",
  "page-padding": "24px",
  "status-success-bg": "#e8f7ed",
  "status-success-border": "#b7ebc6",
  "space-1": "4px",
  "space-2": "8px",
  "space-3": "12px",
  "space-4": "16px",
  "space-5": "20px",
  "space-6": "24px",
  "space-8": "32px",
  "space-10": "40px"
} as const;

export const tokenNumber = (name: keyof typeof tokens): number => Number.parseFloat(tokens[name]);

export const tokenCss = `:root { ${Object.entries(tokens).map(([name, value]) => `--${name}: ${value};`).join(" ")} }`;
